// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClearHandler(ReducerEventContext ctx);
        public event ClearHandler? OnClear;

        public void Clear()
        {
            conn.InternalCallReducer(new Reducer.Clear(), this.SetCallReducerFlags.ClearFlags);
        }

        public bool InvokeClear(ReducerEventContext ctx, Reducer.Clear args)
        {
            if (OnClear == null) return false;
            OnClear(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Clear : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "Clear";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ClearFlags;
        public void Clear(CallReducerFlags flags) => ClearFlags = flags;
    }
}
