// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClientDisconnectedHandler(ReducerEventContext ctx);
        public event ClientDisconnectedHandler? OnClientDisconnected;

        public bool InvokeClientDisconnected(ReducerEventContext ctx, Reducer.ClientDisconnected args)
        {
            if (OnClientDisconnected == null) return false;
            OnClientDisconnected(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ClientDisconnected : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "ClientDisconnected";
        }
    }
}
