// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.
// <auto-generated />

#nullable enable

using System;
using SpacetimeDB;

namespace SpacetimeDB.Types
{
	public enum ReducerType
	{
		None,
		SendMessage,
		SetName,
	}

	public interface IReducerArgs : IReducerArgsBase
	{
		ReducerType ReducerType { get; }
		bool InvokeHandler(ReducerEvent reducerEvent);
	}

	public partial class ReducerEvent : ReducerEventBase
	{
		public IReducerArgs Args { get; }

		public string ReducerName => Args.ReducerName;

		[Obsolete("ReducerType is deprecated, please match directly on type of .Args instead.")]
		public ReducerType Reducer => Args.ReducerType;

		public ReducerEvent(IReducerArgs args) : base() => Args = args;
		public ReducerEvent(ClientApi.Event dbEvent, IReducerArgs args) : base(dbEvent) => Args = args;

		[Obsolete("Accessors that implicitly cast `Args` are deprecated, please match `Args` against the desired type explicitly instead.")]
		public SendMessageArgsStruct SendMessageArgs => (SendMessageArgsStruct)Args;
		[Obsolete("Accessors that implicitly cast `Args` are deprecated, please match `Args` against the desired type explicitly instead.")]
		public SetNameArgsStruct SetNameArgs => (SetNameArgsStruct)Args;

		public override bool InvokeHandler() => Args.InvokeHandler(this);
	}

	public class SpacetimeDBClient : SpacetimeDBClientBase
	{
		protected SpacetimeDBClient()
		{
			clientDB.AddTable<Message>();
			clientDB.AddTable<User>();
		}

		public static readonly SpacetimeDBClient instance = new();

		protected override ReducerEventBase? ReducerEventFromDbEvent(ClientApi.Event dbEvent)
		{
			var argBytes = dbEvent.FunctionCall.ArgBytes;
			IReducerArgs? args = dbEvent.FunctionCall.Reducer switch {
				"send_message" => BSATNHelpers.FromProtoBytes<SendMessageArgsStruct>(argBytes),
				"set_name" => BSATNHelpers.FromProtoBytes<SetNameArgsStruct>(argBytes),
				_ => null
			};
			return args is null ? null : new ReducerEvent(dbEvent, args);
		}
	}

	#if UNITY_5_3_OR_NEWER
	public class NetworkManager : UnityEngine.MonoBehaviour
	{
		private void OnDestroy() => SpacetimeDBClient.instance.Close();
		private void Update() => SpacetimeDBClient.instance.Update();
	}
	#endif
}
