// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.
// <auto-generated />

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.ClientApi
{
	[SpacetimeDB.Type]
	[DataContract]
	public partial class OneOffQueryResponse
	{
		[DataMember(Name = "message_id")]
		public System.Collections.Generic.List<byte> MessageId;
		[DataMember(Name = "error")]
		public string? Error;
		[DataMember(Name = "tables")]
		public System.Collections.Generic.List<SpacetimeDB.ClientApi.OneOffTable> Tables;
		[DataMember(Name = "total_host_execution_duration")]
		public SpacetimeDB.TimeDuration TotalHostExecutionDuration;

		public OneOffQueryResponse(
			System.Collections.Generic.List<byte> MessageId,
			string? Error,
			System.Collections.Generic.List<SpacetimeDB.ClientApi.OneOffTable> Tables,
			SpacetimeDB.TimeDuration TotalHostExecutionDuration
		)
		{
			this.MessageId = MessageId;
			this.Error = Error;
			this.Tables = Tables;
			this.TotalHostExecutionDuration = TotalHostExecutionDuration;
		}

		public OneOffQueryResponse()
		{
			this.MessageId = new();
			this.Tables = new();
			this.TotalHostExecutionDuration = new();
		}

	}
}
