name: Git tree checks

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  merge_group:
permissions: read-all

jobs:
  check_base_ref:
    name: Only release branches may merge into master
    runs-on: ubuntu-latest
    steps:
      - id: not_based_on_master
        if: |
          github.event_name == 'pull_request' &&
          github.event.pull_request.base.ref == 'master' &&
          ! startsWith(github.event.pull_request.head.ref, 'release/')
        run: |
          echo 'Only `release/*` branches are allowed to merge into `master`.'
          echo 'Maybe your PR should be merging into `staging`?'
          exit 1
