name: Test Suite

on:
  push:
    branches:
      - staging
  pull_request:

jobs:
  unity-testsuite:
    runs-on: ubuntu-latest
    steps:
      - name: Export secrets
        run: |
          echo "${{ secrets.SSH_KEY }}" >> id_rsa
          chmod 600 id_rsa
          echo "UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}" >> exported_secrets
          echo "UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}" >> exported_secrets
          echo "UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}" >> exported_secrets
          file exported_secrets
          wc -c exported_secrets
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i id_rsa exported_secrets ubuntu@"${{ secrets.EXPORT_MACHINE }}":
